# Generated by Django 5.0.2 on 2024-03-31 22:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=app.models.unique_img_name),
        ),
    ]
