# Generated by Django 5.0.2 on 2024-03-31 23:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guest_check_in_guest_check_out_guest_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(default='guests/default.png', null=True, upload_to=app.models.unique_img_name),
        ),
    ]
